Update ST

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -52,6 +52,8 @@ jobs:
         with:
           name: jest-report
           path: jest-report
+        
+
 
       # 8. Upload Playwright Report (optional)
       - name: Upload Playwright Report
@@ -79,34 +81,45 @@ jobs:
           /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
 
   deploy-report:
-    runs-on: ubuntu-latest
-    needs: test   # run after jest job
+   runs-on: ubuntu-latest
+   needs: test
 
-    permissions:
-      pages: write
-      id-token: write
-      contents: read
+   permissions:
+    pages: write
+    id-token: write
+    contents: read
 
-    steps:
-      - uses: actions/checkout@v4
+   steps:
+    - uses: actions/checkout@v4
 
-      - name: Download Jest Report Artifact
-        uses: actions/download-artifact@v4
-        with:
-          name: jest-report
-          path: jest-report
+    - name: Download Jest Report Artifact
+      uses: actions/download-artifact@v4
+      with:
+        name: jest-report
+        path: jest-report
 
-      # If using parallel shards, download all
-      - name: Setup GitHub Pages
-        uses: actions/configure-pages@v5
+    - name: Rename report to index.html
+      run: |
+        echo "Checking jest-report folder"
+        ls -R jest-report || echo "jest-report missing"
 
-      - name: Upload Pages Artifact
-        uses: actions/upload-pages-artifact@v3
-        with:
-          path: jest-report
+        if [ -f "jest-report/report.html" ]; then
+          mv jest-report/report.html jest-report/index.html
+          echo "Renamed report.html -> index.html"
+        else
+          echo "report.html not found"
+        fi
 
-      - name: Deploy to GitHub Pages
-        uses: actions/deploy-pages@v4
+    - name: Setup GitHub Pages
+      uses: actions/configure-pages@v5
+
+    - name: Upload Pages Artifact
+      uses: actions/upload-pages-artifact@v3
+      with:
+        path: jest-report
+
+    - name: Deploy to GitHub Pages
+      uses: actions/deploy-pages@v4
 
 
 
